name: rajas_first_asar_game
description: "Raja's First Asar Gaming Assignment"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.7
  auto_route: ^9.2.2
  get_it: ^8.0.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter_clean_architecture: ^6.0.1
  dartz: ^0.10.1
  logger: ^2.5.0
  json_annotation:
  freezed_annotation:
  build_runner:
  freezed:
  json_serializable:
  test: ^1.25.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  

flutter:

  uses-material-design: true

